//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PumpTable
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string Code { get; set; }
        public int State { get; set; }
    }
}
