//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PumpTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PumpTable()
        {
            this.HistoryTables = new HashSet<HistoryTable>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StationId { get; set; }
        public string Position { get; set; }
        public int State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryTable> HistoryTables { get; set; }
        public virtual StationTable StationTable { get; set; }
    }
}
