//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAPI
{
    using DataAPI.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PumpTable
    {
        public int Id { get; set; }
        public int StationId { get; set; }
        public string Position { get; set; }
        public int State { get; set; }
    
        public virtual StationTable StationTable { get; set; }

        public static string RetrieveStationName(int StationId)
        {
            var myEntity = new DATNDBEntities();
            StationTable retStation = myEntity.StationTables.Include("Id")
                                      .Where(station => station.Id == StationId)
                                      .Select(station => new StationTable()
                                      {
                                          Id = station.Id,
                                          Name = station.Name,
                                          Address = station.Address
                                      }).FirstOrDefault<StationTable>();

            if (retStation == null)
            {
                return "";
            }
            else
            {
                return retStation.Name;
            }
        }

        public PumpModel ToPumpModel() 
        {
            return new PumpModel
            {
                StationName = RetrieveStationName(StationId),
                Position = Position,
                State = State
            };
        }
    }
}
